--question1
CREATE TABLE SKILL (SkillNo INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY , SkillName NVARCHAR2(255) NOT NULL, Note Long);
CREATE TABLE DEPARTMENT (DeptNo INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY , DeptName NVARCHAR2(255) NOT NULL, Note Long);
CREATE TABLE EMPLOYEE(
	 EmpNo INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY ,
	 EmpName NVARCHAR2(255) NOT NULL,
	 BirthDay DATE NOT NULL,
	 DeptNo INT NOT NULL,
	 MgrNo INT NOT NULL,
	 StartDate DATE NOT NULL,
	 Salary NUMBER,
	 ELevel INT NOT NULL CHECK(ELevel < 8 AND ELevel > 0),
	 Status INT NOT NULL CHECK(Status < 3 AND Status >= 0),
	 Note LONG
);
CREATE TABLE EMP_SKILL(
	 SkillNo INT REFERENCES SKILL(SkillNo) NOT NULL,
	 EmpNo INT REFERENCES EMPLOYEE(EmpNo) NOT NULL,
	 SkillLevel INT NOT NULL CHECK(SkillLevel < 4 AND SkillLevel > 0),
	 RegDate DATE NOT NULL,
	 Description LONG NOT NULL ,
     PRIMARY KEY(SkillNo, EmpNo)
	 --? SkillLevel: skill level of the employee (accepts value range from 1 to 3 only).
	 );
--QUESTION 2
ALTER TABLE EMPLOYEE ADD Email NVARCHAR2(50) UNIQUE;
ALTER TABLE EMPLOYEE MODIFY( MgrNo INT default 0 );
ALTER TABLE EMPLOYEE MODIFY( Status INT default 0 );
--QUESTION 3
ALTER TABLE EMPLOYEE ADD FOREIGN KEY(DeptNo)REFERENCES DEPARTMENT(DeptNo);
ALTER TABLE EMP_SKILL DROP COLUMN Description;
--QUESTION 4
--INSERT SKILL
INSERT INTO SKILL(SkillName)VALUES(N'SKILL1');
INSERT INTO SKILL(SkillName)VALUES(N'SKILL2');
INSERT INTO SKILL(SkillName)VALUES(N'SKILL3');
INSERT INTO SKILL(SkillName)VALUES(N'SKILL4');
INSERT INTO SKILL(SkillName)VALUES(N'SKILL5');
----insert department
INSERT INTO DEPARTMENT(DeptName, Note)
VALUES(N'dep1', -- DeptName - nvarchar(255)
N''				-- Note - nvarchar(max)
	);
INSERT INTO DEPARTMENT(DeptName, Note)
VALUES(N'dep2', -- DeptName - nvarchar(255)
N''				-- Note - nvarchar(max)
	);
INSERT INTO DEPARTMENT(DeptName, Note)
VALUES(N'dep3', -- DeptName - nvarchar(255)
N''				-- Note - nvarchar(max)
	);
INSERT INTO DEPARTMENT(DeptName, Note)
VALUES(N'dep4', -- DeptName - nvarchar(255)
N''				-- Note - nvarchar(max)
	);
INSERT INTO DEPARTMENT(DeptName, Note)
VALUES(N'dep5', -- DeptName - nvarchar(255)
N''				-- Note - nvarchar(max)
	);
----insert emp
INSERT INTO EMPLOYEE(EmpName, BirthDay, DeptNo, MgrNo, StartDate, Salary, ELevel, Status, Note, Email)
VALUES(N'em1', -- EmpName - nvarchar(255)
(SELECT SYSDATE FROM DUAL),	   -- BirthDay - datetime
1	,		   -- DeptNo - int
0	,		   -- MgrNo - int
(SELECT SYSDATE FROM DUAL),	   -- StartDate - date
0,		   -- Salary - money
1	,		   -- Level - int
0	,		   -- Status - int
N'',		   -- Note - nvarchar(max)
N'1'			   -- Email - nvarchar(50)
	);
INSERT INTO EMPLOYEE(EmpName, BirthDay, DeptNo, MgrNo, StartDate, Salary, ELevel, Status, Note, Email)
VALUES(N'em2', -- EmpName - nvarchar(255)
(SELECT SYSDATE FROM DUAL),	   -- BirthDay - datetime
2	,		   -- DeptNo - int
0	,		   -- MgrNo - int
(SELECT SYSDATE FROM DUAL),	   -- StartDate - date
0,		   -- Salary - money
1	,		   -- Level - int
0	,		   -- Status - int
N'',		   -- Note - nvarchar(max)
N'2'			   -- Email - nvarchar(50)
	);

INSERT INTO EMPLOYEE(EmpName, BirthDay, DeptNo, MgrNo, StartDate, Salary, ELevel, Status, Note, Email)
VALUES(N'em3', -- EmpName - nvarchar(255)
(SELECT SYSDATE FROM DUAL),	   -- BirthDay - datetime
3	,		   -- DeptNo - int
0	,		   -- MgrNo - int
(SELECT SYSDATE FROM DUAL),	   -- StartDate - date
0,		   -- Salary - money
1	,		   -- Level - int
0	,		   -- Status - int
N'',		   -- Note - nvarchar(max)
N'3'			   -- Email - nvarchar(50)
	);

INSERT INTO EMPLOYEE(EmpName, BirthDay, DeptNo, MgrNo, StartDate, Salary, ELevel, Status, Note, Email)
VALUES(N'em4', -- EmpName - nvarchar(255)
(SELECT SYSDATE FROM DUAL),	   -- BirthDay - datetime
4	,		   -- DeptNo - int
0	,		   -- MgrNo - int
(SELECT SYSDATE FROM DUAL),	   -- StartDate - date
0,		   -- Salary - money
4	,		   -- Level - int
0	,		   -- Status - int
N'',		   -- Note - nvarchar(max)
N'4'			   -- Email - nvarchar(50)
	);

INSERT INTO EMPLOYEE(EmpName, BirthDay, DeptNo, MgrNo, StartDate, Salary, ELevel, Status, Note, Email)
VALUES(N'em5', -- EmpName - nvarchar(255)
(SELECT SYSDATE FROM DUAL),	   -- BirthDay - datetime
5	,		   -- DeptNo - int
0	,		   -- MgrNo - int
(SELECT SYSDATE FROM DUAL),	   -- StartDate - date
0,		   -- Salary - money
5	,		   -- Level - int
0	,		   -- Status - int
N'',		   -- Note - nvarchar(max)
N'6'			   -- Email - nvarchar(50)
	);
--view
CREATE VIEW EMPLOYEE_TRACKING AS 
SELECT EmpNo, EmpName, ELevel
FROM EMPLOYEE
WHERE ELevel >= 3 AND ELevel <= 5;

